### PR TITLE
Added commits chunks, Debug mode, etc

### LINKED ISSUE #16: Env Filter limit
C:\Program Files\Git\mingw64/libexec/git-core\git-redate: line 103: syntax error: unexpected end of file

When redating much commits then 44 on the windows system we can look on the filter-branch --env-filter limit by 578 lines. 

so i try to look of solution.

### PR DESCRIPTION
**Pull request by ghost**
- Chunks collection
- Debug operation (Operation progress)
- Fix bug with last line (last commit) in tempfile
- Added some params

Tested on 2000+ commits - spent some time (5 min) but working.
fixed #16

### CODE REVIEW

**Comment by ghost** [comment]
@AaronVasquez can you help me with script params? it seems don't work together 👎

**Comment by AaronVasquez** [comment]
Can you explain what you mean?

**Comment by ghost** [comment]
@AaronVasquez i mean something about `redate.sh -d --all` it doesnt work.
only one param can recognized by script... It was hard for me. I cant understand why did this shit happens)

image
Look at here - i call `redate.sh --debug --all` only `debug` param applied to task. =((

I look for getopts by native function in bash - but doesnt work or i made something wrong.

**Comment by ghost** [comment]
And i think need to update your main gif on the front of repo and some change README.md)))

**Pull request merged**
